# docker-compose.yml
services:
  db:
    build: .
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: "drizzle-crash-course"
      TZ: "Asia/Tokyo"
      LANG: "ja_JP.UTF-8"
      LANGUAGE: "ja_JP:ja"
      LC_ALL: "ja_JP.UTF-8"